spring:
  cloud:
    openfeign:
      client:
        config:
          chuck:
            url: http://chuck:8080
management:
  server:
    port: 8081
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
